/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as RespondSubmissionIdRouteImport } from './routes/respond/$submissionId'
import { Route as AuthFormsIndexRouteImport } from './routes/_auth/forms/index'
import { Route as AuthFormsCreateRouteImport } from './routes/_auth/forms/create'
import { Route as AuthFormsFormIdRouteImport } from './routes/_auth/forms/$formId'
import { Route as AuthFormsFormIdIndexRouteImport } from './routes/_auth/forms/$formId/index'
import { Route as AuthFormsFormIdPreviewRouteImport } from './routes/_auth/forms/$formId/preview'
import { Route as AuthFormsFormIdEditRouteImport } from './routes/_auth/forms/$formId/edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const RespondSubmissionIdRoute = RespondSubmissionIdRouteImport.update({
  id: '/respond/$submissionId',
  path: '/respond/$submissionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthFormsIndexRoute = AuthFormsIndexRouteImport.update({
  id: '/forms/',
  path: '/forms/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFormsCreateRoute = AuthFormsCreateRouteImport.update({
  id: '/forms/create',
  path: '/forms/create',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFormsFormIdRoute = AuthFormsFormIdRouteImport.update({
  id: '/forms/$formId',
  path: '/forms/$formId',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFormsFormIdIndexRoute = AuthFormsFormIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthFormsFormIdRoute,
} as any)
const AuthFormsFormIdPreviewRoute = AuthFormsFormIdPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => AuthFormsFormIdRoute,
} as any)
const AuthFormsFormIdEditRoute = AuthFormsFormIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AuthFormsFormIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/respond/$submissionId': typeof RespondSubmissionIdRoute
  '/forms/$formId': typeof AuthFormsFormIdRouteWithChildren
  '/forms/create': typeof AuthFormsCreateRoute
  '/forms/': typeof AuthFormsIndexRoute
  '/forms/$formId/edit': typeof AuthFormsFormIdEditRoute
  '/forms/$formId/preview': typeof AuthFormsFormIdPreviewRoute
  '/forms/$formId/': typeof AuthFormsFormIdIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/respond/$submissionId': typeof RespondSubmissionIdRoute
  '/': typeof AuthIndexRoute
  '/forms/create': typeof AuthFormsCreateRoute
  '/forms': typeof AuthFormsIndexRoute
  '/forms/$formId/edit': typeof AuthFormsFormIdEditRoute
  '/forms/$formId/preview': typeof AuthFormsFormIdPreviewRoute
  '/forms/$formId': typeof AuthFormsFormIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/respond/$submissionId': typeof RespondSubmissionIdRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/forms/$formId': typeof AuthFormsFormIdRouteWithChildren
  '/_auth/forms/create': typeof AuthFormsCreateRoute
  '/_auth/forms/': typeof AuthFormsIndexRoute
  '/_auth/forms/$formId/edit': typeof AuthFormsFormIdEditRoute
  '/_auth/forms/$formId/preview': typeof AuthFormsFormIdPreviewRoute
  '/_auth/forms/$formId/': typeof AuthFormsFormIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/respond/$submissionId'
    | '/forms/$formId'
    | '/forms/create'
    | '/forms/'
    | '/forms/$formId/edit'
    | '/forms/$formId/preview'
    | '/forms/$formId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/respond/$submissionId'
    | '/'
    | '/forms/create'
    | '/forms'
    | '/forms/$formId/edit'
    | '/forms/$formId/preview'
    | '/forms/$formId'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/respond/$submissionId'
    | '/_auth/'
    | '/_auth/forms/$formId'
    | '/_auth/forms/create'
    | '/_auth/forms/'
    | '/_auth/forms/$formId/edit'
    | '/_auth/forms/$formId/preview'
    | '/_auth/forms/$formId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  RespondSubmissionIdRoute: typeof RespondSubmissionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/respond/$submissionId': {
      id: '/respond/$submissionId'
      path: '/respond/$submissionId'
      fullPath: '/respond/$submissionId'
      preLoaderRoute: typeof RespondSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forms/': {
      id: '/_auth/forms/'
      path: '/forms'
      fullPath: '/forms/'
      preLoaderRoute: typeof AuthFormsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forms/create': {
      id: '/_auth/forms/create'
      path: '/forms/create'
      fullPath: '/forms/create'
      preLoaderRoute: typeof AuthFormsCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forms/$formId': {
      id: '/_auth/forms/$formId'
      path: '/forms/$formId'
      fullPath: '/forms/$formId'
      preLoaderRoute: typeof AuthFormsFormIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forms/$formId/': {
      id: '/_auth/forms/$formId/'
      path: '/'
      fullPath: '/forms/$formId/'
      preLoaderRoute: typeof AuthFormsFormIdIndexRouteImport
      parentRoute: typeof AuthFormsFormIdRoute
    }
    '/_auth/forms/$formId/preview': {
      id: '/_auth/forms/$formId/preview'
      path: '/preview'
      fullPath: '/forms/$formId/preview'
      preLoaderRoute: typeof AuthFormsFormIdPreviewRouteImport
      parentRoute: typeof AuthFormsFormIdRoute
    }
    '/_auth/forms/$formId/edit': {
      id: '/_auth/forms/$formId/edit'
      path: '/edit'
      fullPath: '/forms/$formId/edit'
      preLoaderRoute: typeof AuthFormsFormIdEditRouteImport
      parentRoute: typeof AuthFormsFormIdRoute
    }
  }
}

interface AuthFormsFormIdRouteChildren {
  AuthFormsFormIdEditRoute: typeof AuthFormsFormIdEditRoute
  AuthFormsFormIdPreviewRoute: typeof AuthFormsFormIdPreviewRoute
  AuthFormsFormIdIndexRoute: typeof AuthFormsFormIdIndexRoute
}

const AuthFormsFormIdRouteChildren: AuthFormsFormIdRouteChildren = {
  AuthFormsFormIdEditRoute: AuthFormsFormIdEditRoute,
  AuthFormsFormIdPreviewRoute: AuthFormsFormIdPreviewRoute,
  AuthFormsFormIdIndexRoute: AuthFormsFormIdIndexRoute,
}

const AuthFormsFormIdRouteWithChildren = AuthFormsFormIdRoute._addFileChildren(
  AuthFormsFormIdRouteChildren,
)

interface AuthRouteChildren {
  AuthIndexRoute: typeof AuthIndexRoute
  AuthFormsFormIdRoute: typeof AuthFormsFormIdRouteWithChildren
  AuthFormsCreateRoute: typeof AuthFormsCreateRoute
  AuthFormsIndexRoute: typeof AuthFormsIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthIndexRoute: AuthIndexRoute,
  AuthFormsFormIdRoute: AuthFormsFormIdRouteWithChildren,
  AuthFormsCreateRoute: AuthFormsCreateRoute,
  AuthFormsIndexRoute: AuthFormsIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  RespondSubmissionIdRoute: RespondSubmissionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
