import { tv } from 'tailwind-variants'

export const optionsSelector = tv({
  slots: {
    container: ['space-y-3'],
    freeTextContainer: [
      'mt-4',
      'pt-4',
      'border-t',
      'border-neutral-100',
      'dark:border-neutral-700',
    ],
    freeTextInput: [
      'w-full',
      'px-4',
      'py-3',
      'text-sm',
      'rounded-xl',
      'border',
      'border-neutral-200',
      'dark:border-neutral-600',
      'bg-neutral-50',
      'dark:bg-neutral-700/50',
      'text-neutral-900',
      'dark:text-neutral-100',
      'placeholder:text-neutral-400',
      'dark:placeholder:text-neutral-500',
      'focus:outline-none',
      'focus:ring-2',
      'focus:ring-blue-500/20',
      'focus:border-blue-500',
      'dark:focus:border-blue-400',
      'resize-none',
      'transition-all',
      'duration-200',
      'disabled:opacity-50',
      'disabled:cursor-not-allowed',
    ],
    submitButton: [
      'w-full',
      'mt-4',
      'py-3',
      'px-6',
      'rounded-xl',
      'font-semibold',
      'text-sm',
      'bg-neutral-900',
      'text-white',
      'hover:bg-neutral-800',
      'dark:bg-neutral-50',
      'dark:text-neutral-900',
      'dark:hover:bg-neutral-200',
      'transition-all',
      'duration-200',
      'disabled:opacity-50',
      'disabled:cursor-not-allowed',
    ],
  },
})

export const optionItem = tv({
  slots: {
    button: [
      'w-full',
      'flex',
      'items-center',
      'gap-3',
      'px-4',
      'py-3',
      'rounded-xl',
      'border-2',
      'transition-all',
      'duration-200',
      'cursor-pointer',
      'text-left',
    ],
    indicator: [
      'flex-shrink-0',
      'w-5',
      'h-5',
      'border-2',
      'flex',
      'items-center',
      'justify-center',
      'transition-all',
      'duration-200',
    ],
    indicatorInner: ['w-2.5', 'h-2.5', 'transition-all', 'duration-200'],
    label: ['flex-1', 'text-sm', 'font-medium'],
  },
  variants: {
    selected: {
      true: {
        button: ['border-blue-500', 'bg-blue-50', 'dark:border-blue-400', 'dark:bg-blue-900/20'],
        indicator: ['border-blue-500', 'dark:border-blue-400'],
        indicatorInner: ['bg-blue-500', 'dark:bg-blue-400'],
        label: ['text-blue-700', 'dark:text-blue-300'],
      },
      false: {
        button: [
          'border-neutral-200',
          'dark:border-neutral-600',
          'bg-neutral-50',
          'dark:bg-neutral-700/50',
          'hover:border-neutral-300',
          'dark:hover:border-neutral-500',
          'hover:bg-neutral-100',
          'dark:hover:bg-neutral-700',
        ],
        indicator: ['border-neutral-300', 'dark:border-neutral-500'],
        indicatorInner: ['bg-transparent'],
        label: ['text-neutral-700', 'dark:text-neutral-300'],
      },
    },
    selectionType: {
      radio: {
        indicator: ['rounded-full'],
        indicatorInner: ['rounded-full'],
      },
      checkbox: {
        indicator: ['rounded'],
        indicatorInner: ['rounded-sm'],
      },
    },
    disabled: {
      true: {
        button: ['opacity-50', 'cursor-not-allowed', 'pointer-events-none'],
      },
    },
  },
  defaultVariants: {
    selected: false,
    selectionType: 'radio',
    disabled: false,
  },
})
