import type { typography } from './const'
import type { HTMLAttributes, ReactNode } from 'react'
import type { VariantProps } from 'tailwind-variants'

export interface TypographyProps
  extends HTMLAttributes<HTMLSpanElement>, VariantProps<typeof typography> {
  children: ReactNode
  className?: string
  as?:
    | 'span'
    | 'p'
    | 'div'
    | 'label'
    | 'h1'
    | 'h2'
    | 'h3'
    | 'h4'
    | 'h5'
    | 'h6'
    | 'small'
    | 'strong'
    | 'em'
    | 'blockquote'
    | 'cite'
    | 'code'
    | 'pre'
    | 'abbr'
    | 'address'
    | 'del'
    | 'ins'
    | 'mark'
    | 'sub'
    | 'sup'
    | 'time'
    | 'var'
    | 's'
    | 'u'
    | 'i'
    | 'b'
    | 'q'
    | 'samp'
    | 'kbd'
    | 'dfn'
    | 'ruby'
    | 'rt'
    | 'rp'
    | 'bdi'
    | 'bdo'
    | 'wbr'
    | 'data'
    | 'meter'
    | 'progress'
}
