import { tv } from 'tailwind-variants'

export const chatPanel = tv({
  slots: {
    container: ['flex', 'flex-col', 'h-full'],
    messageList: ['flex-1', 'overflow-y-auto', 'p-4', 'space-y-1'],
    inputArea: ['p-4', 'bg-transparent'],
    inputCard: [
      'bg-white',
      'dark:bg-neutral-800',
      'rounded-2xl',
      'shadow-md',
      'dark:shadow-neutral-900/50',
      'border',
      'border-neutral-100',
      'dark:border-neutral-700',
      'p-4',
    ],
    inputTextarea: [
      'w-full',
      'resize-none',
      'outline-none',
      'bg-transparent',
      'text-neutral-900',
      'dark:text-neutral-50',
      'placeholder:text-neutral-400',
      'dark:placeholder:text-neutral-500',
      'text-base',
      'leading-relaxed',
    ],
    inputButtonContainer: ['flex', 'justify-end', 'mt-3'],
    inputButton: [
      'inline-flex',
      'items-center',
      'justify-center',
      'px-5',
      'py-2',
      'text-sm',
      'font-semibold',
      'rounded-xl',
      'bg-neutral-900',
      'text-white',
      'hover:bg-neutral-800',
      'dark:bg-neutral-50',
      'dark:text-neutral-900',
      'dark:hover:bg-neutral-200',
      'disabled:opacity-50',
      'disabled:cursor-not-allowed',
      'transition-colors',
      'duration-200',
      'focus-visible:outline-none',
      'focus-visible:ring-2',
      'focus-visible:ring-offset-2',
      'focus-visible:ring-neutral-950',
      'dark:focus-visible:ring-neutral-300',
    ],
    completeMessage: [
      'text-center',
      'py-4',
      'px-6',
      'bg-neutral-100',
      'dark:bg-neutral-800',
      'border-t',
      'border-neutral-200',
      'dark:border-neutral-700',
    ],
  },
})
